title: Jevita Saldanha
logo: "https://github.com/reneda/images/blob/master/jevitapurple.png?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  <br>
  <a href="mailto:jevita279@gmail.com">jevita279@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/jevita279/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/reneda/">Github</a> 
theme: jekyll-theme-minimal
