title: jevita
logo: "https://github.com/reneda/images/blob/master/Untitled.png?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior Frontend Engineer
  <br><br>
  <a href="mailto:aashima.ahuja811@gmail.com">aashima.ahuja811@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/aashimaahuja/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/aashimaahuja/">Gihub</a> 
theme: jekyll-theme-minimal
